### ISSUE TITLE
Um, how do I access images / assets?

### ISSUE THREAD

**Issue by thathurtabit** [wbkd/yet-another-webpack-es6-starterkit#15]
I'm probably missing something simple, but I can't seem to find my assets (images/ video). Is Webpack in Dev moving the HTML somewhere? Thanks.

**Comment by kurorido** [comment]
1. install file loader
`npm install file-loader --dev`

2. modify webpack.config-helper.js

```
        {
          test: /\.(jpe?g|png|gif|svg)$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[path][name].[ext]'
              }
            }
          ]
        }
```

3. add images folder in root folder
4. import image file in index.js

**Comment by thathurtabit** [comment]
Might be worth adding this in as default as it's pretty much always going to be used?

**Comment by moklick** [comment]
good point :) We've just updated our webpack config https://github.com/wbkd/yet-another-webpack-es6-starterkit/blob/master/webpack/webpack.common.js#L39

**Comment by dertuerke** [comment]
hi i try to add assets from this path to the index.html
`assets/images/logo.png`

But it not working :S
