### ISSUE TITLE
Failing to load SVG's

### ISSUE THREAD

**Issue by natezerk** [wbkd/yet-another-webpack-es6-starterkit#2]
Fails to load in SVG's for me.
I've added the following into `webpack.config.helper.js` in the rules section.
```
{
      test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
      loader: 'url-loader'
}
```

And getting `You may need an appropriate loader to handle this file type.` on all the SVG types. Any suggestions?

**Comment by moklick** [comment]
Try to use `raw-loader` for loading SVG's https://github.com/webpack-contrib/url-loader/issues/6

**Comment by alonronin** [comment]
you can use `url-loader` to use with `<img />` tags at html and css `background-image` rule.
